import { useQuery, useMutation } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Trash2, FileText, Linkedin, Video, RefreshCw, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { queryClient } from '@/lib/queryClient';

interface LunaDraft {
  id: string;
  title: string;
  platform: string;
  content: string;
  telegramChatId: string | null;
  createdAt: string;
}

export default function AdminLunaDraftsPage() {
  const { toast } = useToast();

  const { data: drafts, isLoading, refetch } = useQuery<LunaDraft[]>({
    queryKey: ['admin-luna-drafts'],
    queryFn: async () => {
      const response = await fetch('/api/admin/luna/drafts', {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to fetch drafts');
      return response.json();
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const response = await fetch(`/api/admin/luna/drafts/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to delete draft');
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin-luna-drafts'] });
      toast({ title: 'Draft deleted', description: 'The draft has been removed.' });
    },
    onError: () => {
      toast({ title: 'Error', description: 'Failed to delete draft', variant: 'destructive' });
    },
  });

  const copyToClipboard = (content: string) => {
    navigator.clipboard.writeText(content);
    toast({ title: 'Copied', description: 'Content copied to clipboard' });
  };

  const getPlatformIcon = (platform: string) => {
    switch (platform) {
      case 'linkedin':
        return <Linkedin className="h-4 w-4" />;
      case 'video_script':
        return <Video className="h-4 w-4" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  const getPlatformColor = (platform: string) => {
    switch (platform) {
      case 'linkedin':
        return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300';
      case 'video_script':
        return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300';
      default:
        return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300';
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  if (isLoading) {
    return (
      <div className="container mx-auto p-6">
        <div className="flex items-center justify-center py-20">
          <RefreshCw className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Luna Drafts</h1>
          <p className="text-muted-foreground mt-1">
            Content drafts generated by Luna via Telegram
          </p>
        </div>
        <Button variant="outline" onClick={() => refetch()} data-testid="button-refresh-drafts">
          <RefreshCw className="h-4 w-4 mr-2" />
          Refresh
        </Button>
      </div>

      {!drafts || drafts.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <FileText className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium">No drafts yet</h3>
            <p className="text-muted-foreground text-center mt-2">
              Message Luna on Telegram with "hi" or "/start" to generate your first drafts.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {drafts.map((draft) => (
            <Card key={draft.id} data-testid={`card-draft-${draft.id}`}>
              <CardHeader className="flex flex-row items-start justify-between gap-4 space-y-0 pb-2">
                <div className="space-y-1">
                  <CardTitle className="text-lg">{draft.title}</CardTitle>
                  <CardDescription>{formatDate(draft.createdAt)}</CardDescription>
                </div>
                <div className="flex items-center gap-2">
                  <Badge className={getPlatformColor(draft.platform)}>
                    {getPlatformIcon(draft.platform)}
                    <span className="ml-1 capitalize">{draft.platform.replace('_', ' ')}</span>
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-muted/50 rounded-lg p-4">
                  <pre className="whitespace-pre-wrap text-sm font-mono">{draft.content}</pre>
                </div>
                <div className="flex items-center justify-end gap-2">
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => copyToClipboard(draft.content)}
                    data-testid={`button-copy-${draft.id}`}
                  >
                    <Copy className="h-4 w-4 mr-2" />
                    Copy
                  </Button>
                  <Button
                    variant="destructive"
                    size="sm"
                    onClick={() => deleteMutation.mutate(draft.id)}
                    disabled={deleteMutation.isPending}
                    data-testid={`button-delete-${draft.id}`}
                  >
                    <Trash2 className="h-4 w-4 mr-2" />
                    Delete
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
