export type ToolCategory = {
  id: string;
  name: string;
  description: string;
  icon: string; // lucide icon name
};

export type Tool = {
  slug: string;
  name: string;
  categoryId: string;
  description: string;
  bestFor: string;
  pricing: "free" | "freemium" | "paid";
  priceNote?: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  url: string;
  nadiaPick?: boolean;
  isNew?: boolean;
  quickStart: string[];
  starterPrompt?: string;
};

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: "write", name: "Write and Create Content", description: "AI assistants for writing, editing, and content creation.", icon: "PenLine" },
  { id: "images", name: "Create Images and Graphics", description: "Generate professional visuals without design skills.", icon: "Image" },
  { id: "video", name: "Create Videos", description: "Produce video content without expensive equipment.", icon: "Video" },
  { id: "audio", name: "Create Music and Audio", description: "Generate music, voiceovers, and podcast audio.", icon: "Music" },
  { id: "build", name: "Build Websites and Apps", description: "Create websites and apps without writing code.", icon: "Code" },
  { id: "automate", name: "Automate Your Work", description: "Connect tools and eliminate repetitive tasks.", icon: "Zap" },
  { id: "research", name: "Research and Learn", description: "AI-powered research, summaries, and knowledge tools.", icon: "Search" },
  { id: "brand", name: "Design Your Brand", description: "Logos, presentations, and brand identity tools.", icon: "Palette" },
  { id: "social", name: "Manage Social Media", description: "Schedule, create, and optimize social content.", icon: "Share2" },
  { id: "productivity", name: "Productivity and Organization", description: "Notes, meetings, scheduling, and task management.", icon: "LayoutGrid" },
];

export const TOOLS: Tool[] = [
  // === WRITE AND CREATE CONTENT ===
  {
    slug: "chatgpt",
    name: "ChatGPT",
    categoryId: "write",
    description: "The most popular AI assistant. Excellent for brainstorming, drafting, editing, and conversational tasks. Strong at following complex instructions.",
    bestFor: "Best for versatile writing tasks and creative brainstorming",
    pricing: "freemium",
    priceNote: "Free tier available. Plus from $20/mo",
    difficulty: "beginner",
    url: "https://chat.openai.com",
    nadiaPick: true,
    quickStart: [
      "Go to chat.openai.com and create a free account",
      "Type a specific request: 'Write a 100-word Instagram caption for a wellness brand targeting women 30-45, warm tone, ends with a question'",
      "Ask it to revise: 'Make it shorter and add more personality'",
    ],
    starterPrompt: "You are a content strategist for a women-led small business. Help me create this week's 5 social media posts about [your topic]. Include hooks, body text, and CTAs.",
  },
  {
    slug: "claude",
    name: "Claude",
    categoryId: "write",
    description: "Anthropic's AI assistant. Known for nuanced, thoughtful responses and strong analytical thinking. Excellent at long documents, strategy, and detailed analysis.",
    bestFor: "Best for long-form writing, analysis, and strategic thinking",
    pricing: "freemium",
    priceNote: "Free tier available. Pro from $20/mo",
    difficulty: "beginner",
    url: "https://claude.ai",
    nadiaPick: true,
    quickStart: [
      "Go to claude.ai and create a free account",
      "Try a detailed task: 'Analyze my business idea [describe it] and give me honest feedback on strengths, weaknesses, and what to do first'",
      "Upload a document and ask Claude to summarize, critique, or improve it",
    ],
    starterPrompt: "I'm a solopreneur building [your business]. Act as my strategic advisor. Review my current situation and give me a prioritized 30-day action plan.",
  },
  {
    slug: "gemini",
    name: "Gemini",
    categoryId: "write",
    description: "Google's AI assistant. Integrates with Google Workspace (Docs, Sheets, Gmail). Strong at research tasks because it can access current web information.",
    bestFor: "Best for research and Google Workspace integration",
    pricing: "freemium",
    priceNote: "Free tier available. Advanced from $20/mo",
    difficulty: "beginner",
    url: "https://gemini.google.com",
    quickStart: [
      "Go to gemini.google.com and sign in with your Google account",
      "Ask a research question: 'What are the top 5 trends in [your industry] right now? Include sources'",
      "Try: 'Help me draft a professional email to [recipient] about [topic]. Keep it under 150 words'",
    ],
  },
  {
    slug: "grok",
    name: "Grok",
    categoryId: "write",
    description: "xAI's assistant available on X (Twitter). Has real-time access to X posts and trending topics. Useful for social media content and trend analysis.",
    bestFor: "Best for social media trends and X/Twitter content",
    pricing: "freemium",
    priceNote: "Free on X. Premium with X subscription",
    difficulty: "beginner",
    url: "https://x.com",
    quickStart: [
      "Open X (Twitter) and access Grok from the sidebar",
      "Ask: 'What's trending in [your niche] on X right now?'",
      "Try: 'Write 5 tweet ideas about [your topic] that would get engagement'",
    ],
  },
  {
    slug: "jasper",
    name: "Jasper",
    categoryId: "write",
    description: "Purpose-built for marketing teams. Templates for ads, emails, landing pages, and social posts. Maintains brand voice across all content.",
    bestFor: "Best for marketing copy at scale",
    pricing: "paid",
    priceNote: "From $49/mo",
    difficulty: "intermediate",
    url: "https://jasper.ai",
    quickStart: [
      "Start a 7-day free trial at jasper.ai",
      "Set up your brand voice: upload examples of your existing content",
      "Use a template: try 'Social Media Post' and input your topic and audience",
    ],
  },

  // === CREATE IMAGES AND GRAPHICS ===
  {
    slug: "midjourney",
    name: "MidJourney",
    categoryId: "images",
    description: "The gold standard for AI image generation. Creates stunning, artistic images from text descriptions. Works through Discord.",
    bestFor: "Best for beautiful, editorial-quality images",
    pricing: "paid",
    priceNote: "From $10/mo",
    difficulty: "intermediate",
    url: "https://midjourney.com",
    nadiaPick: true,
    quickStart: [
      "Join midjourney.com and connect your Discord account",
      "In any bot channel, type: /imagine prompt: professional headshot of a woman entrepreneur in a modern office, warm lighting, editorial style",
      "Click the U1-U4 buttons to upscale your favorite variation",
    ],
    starterPrompt: "/imagine prompt: [describe what you want], professional photography, soft natural lighting, editorial quality, 4k --ar 16:9",
  },
  {
    slug: "dalle",
    name: "DALL-E 3",
    categoryId: "images",
    description: "OpenAI's image generator built into ChatGPT. Simple to use because you describe what you want in natural language. Great for quick visuals.",
    bestFor: "Best for quick, simple image generation within ChatGPT",
    pricing: "freemium",
    priceNote: "Limited free images. Unlimited with ChatGPT Plus $20/mo",
    difficulty: "beginner",
    url: "https://chat.openai.com",
    quickStart: [
      "Open ChatGPT and type: 'Create an image of [describe what you want]'",
      "Be specific: include style, colors, mood, and composition details",
      "Ask for variations: 'Make it warmer' or 'Try a different angle'",
    ],
  },
  {
    slug: "canva-ai",
    name: "Canva AI",
    categoryId: "images",
    description: "Design platform with AI features: Magic Design generates layouts, Magic Write creates copy, and Magic Edit modifies images. All within a familiar drag-and-drop editor.",
    bestFor: "Best for non-designers who need polished graphics fast",
    pricing: "freemium",
    priceNote: "Free tier available. Pro from $13/mo",
    difficulty: "beginner",
    url: "https://canva.com",
    nadiaPick: true,
    quickStart: [
      "Open canva.com and click 'Create a design'",
      "Try Magic Design: describe what you need and Canva generates layout options",
      "Edit colors, fonts, and images to match your brand",
    ],
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    categoryId: "images",
    description: "Adobe's AI image generator. Trained on licensed content, making it safer for commercial use. Integrates with Photoshop and Illustrator.",
    bestFor: "Best for commercially safe images and Adobe integration",
    pricing: "freemium",
    priceNote: "Free tier with credits. Included in Creative Cloud",
    difficulty: "beginner",
    url: "https://firefly.adobe.com",
    quickStart: [
      "Go to firefly.adobe.com and sign in with Adobe account",
      "Choose 'Text to Image' and describe your visual",
      "Use style presets (Photo, Art, Graphic) to refine the look",
    ],
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo.AI",
    categoryId: "images",
    description: "AI image generation with fine-tuned models for specific styles. Strong at consistent character design and product photography.",
    bestFor: "Best for consistent style across multiple images",
    pricing: "freemium",
    priceNote: "150 free images/day. Pro from $12/mo",
    difficulty: "intermediate",
    url: "https://leonardo.ai",
    quickStart: [
      "Sign up at leonardo.ai for free daily credits",
      "Choose a fine-tuned model that matches your desired style",
      "Generate and use the 'Image to Image' feature for variations",
    ],
  },

  // === CREATE VIDEOS ===
  {
    slug: "runway",
    name: "Runway",
    categoryId: "video",
    description: "Professional AI video generation and editing. Create videos from text or images. Remove backgrounds, extend clips, and generate motion.",
    bestFor: "Best for AI video generation and professional editing",
    pricing: "freemium",
    priceNote: "Limited free tier. Standard from $12/mo",
    difficulty: "intermediate",
    url: "https://runwayml.com",
    nadiaPick: true,
    quickStart: [
      "Sign up at runwayml.com",
      "Try 'Gen-2': describe a short video scene in text",
      "Or upload an image and animate it with 'Image to Video'",
    ],
  },
  {
    slug: "heygen",
    name: "HeyGen",
    categoryId: "video",
    description: "Create talking-head videos with AI avatars. Type your script, choose an avatar, and generate a professional video. No camera needed.",
    bestFor: "Best for professional talking-head videos without filming",
    pricing: "freemium",
    priceNote: "1 free video. Creator from $24/mo",
    difficulty: "beginner",
    url: "https://heygen.com",
    quickStart: [
      "Sign up at heygen.com",
      "Choose an AI avatar or create one from your own photo",
      "Type your script, select a voice, and generate your video",
    ],
  },
  {
    slug: "capcut",
    name: "CapCut",
    categoryId: "video",
    description: "Free video editor with powerful AI features: auto-captions, background removal, AI effects, and templates. Made by ByteDance (TikTok's parent).",
    bestFor: "Best for quick social media video editing with AI captions",
    pricing: "freemium",
    priceNote: "Free with most features. Pro from $8/mo",
    difficulty: "beginner",
    url: "https://capcut.com",
    quickStart: [
      "Download CapCut (desktop or mobile)",
      "Import a video clip and click 'Auto Captions'",
      "Add a template, adjust timing, and export for social media",
    ],
  },

  // === CREATE MUSIC AND AUDIO ===
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    categoryId: "audio",
    description: "The most realistic AI voice generator. Clone your own voice or use premium voices for podcasts, voiceovers, and audio content.",
    bestFor: "Best for realistic voiceovers and voice cloning",
    pricing: "freemium",
    priceNote: "10 min free/month. Starter from $5/mo",
    difficulty: "beginner",
    url: "https://elevenlabs.io",
    nadiaPick: true,
    quickStart: [
      "Sign up at elevenlabs.io",
      "Choose a voice from the library or clone your own",
      "Paste your script text and click generate",
    ],
  },
  {
    slug: "mureka",
    name: "Mureka",
    categoryId: "audio",
    description: "AI music generation for content creators. Create custom background music, jingles, and soundtracks for your videos and podcasts.",
    bestFor: "Best for custom background music for content",
    pricing: "freemium",
    priceNote: "Free tier available",
    difficulty: "beginner",
    url: "https://mureka.ai",
    isNew: true,
    quickStart: [
      "Go to mureka.ai and create an account",
      "Describe the mood and style of music you need",
      "Download and use in your content (check license terms)",
    ],
  },
  {
    slug: "suno",
    name: "Suno",
    categoryId: "audio",
    description: "Create full songs with AI: lyrics, vocals, and instrumentals. Describe the genre and mood and get a complete track in minutes.",
    bestFor: "Best for creating complete songs and jingles",
    pricing: "freemium",
    priceNote: "10 songs free/day. Pro from $10/mo",
    difficulty: "beginner",
    url: "https://suno.com",
    quickStart: [
      "Go to suno.com and sign in",
      "Describe your song: genre, mood, topic, and style",
      "Generate and download your track",
    ],
  },

  // === BUILD WEBSITES AND APPS ===
  {
    slug: "replit",
    name: "Replit",
    categoryId: "build",
    description: "Build full applications with AI assistance. Describe what you want and Replit's AI agent writes the code, sets up the database, and deploys it.",
    bestFor: "Best for building complete apps without coding experience",
    pricing: "freemium",
    priceNote: "Free tier. Pro from $15/mo",
    difficulty: "intermediate",
    url: "https://replit.com",
    nadiaPick: true,
    quickStart: [
      "Sign up at replit.com",
      "Click 'Create' and describe your app in plain language",
      "Let the AI agent build it, then customize and deploy",
    ],
  },
  {
    slug: "bolt",
    name: "Bolt.new",
    categoryId: "build",
    description: "Build and deploy web apps from a text description. Creates React applications with a visual preview you can edit in real time.",
    bestFor: "Best for quick web app prototypes",
    pricing: "freemium",
    priceNote: "Limited free tier. Pro from $20/mo",
    difficulty: "intermediate",
    url: "https://bolt.new",
    isNew: true,
    quickStart: [
      "Go to bolt.new",
      "Describe the web app you want in the prompt box",
      "Edit the generated code visually and deploy with one click",
    ],
  },
  {
    slug: "framer",
    name: "Framer",
    categoryId: "build",
    description: "Design and publish websites visually with AI assistance. AI generates layouts, copy, and responsive designs. No coding needed.",
    bestFor: "Best for beautiful marketing websites without code",
    pricing: "freemium",
    priceNote: "Free site with Framer branding. Pro from $15/mo",
    difficulty: "beginner",
    url: "https://framer.com",
    quickStart: [
      "Go to framer.com and start a new project",
      "Use 'AI Site' to generate a full website from a description",
      "Customize the design, add your content, and publish",
    ],
  },
  {
    slug: "gamma",
    name: "Gamma",
    categoryId: "build",
    description: "Create presentations, documents, and web pages from a text prompt. Beautiful templates that look professional without design work.",
    bestFor: "Best for quick presentations and pitch decks",
    pricing: "freemium",
    priceNote: "Free tier with credits. Plus from $10/mo",
    difficulty: "beginner",
    url: "https://gamma.app",
    quickStart: [
      "Go to gamma.app and sign up",
      "Click 'Create new' and describe your presentation topic",
      "Edit the generated slides and present or share the link",
    ],
  },

  // === AUTOMATE YOUR WORK ===
  {
    slug: "zapier",
    name: "Zapier",
    categoryId: "automate",
    description: "Connect 6,000+ apps and automate workflows. When something happens in one app, automatically trigger actions in others. No coding required.",
    bestFor: "Best for connecting apps and automating repetitive tasks",
    pricing: "freemium",
    priceNote: "5 free Zaps. Starter from $20/mo",
    difficulty: "beginner",
    url: "https://zapier.com",
    nadiaPick: true,
    quickStart: [
      "Sign up at zapier.com",
      "Create your first Zap: 'When I get a new email subscriber, add them to my Google Sheet'",
      "Turn it on and let it run automatically",
    ],
  },
  {
    slug: "make",
    name: "Make (Integromat)",
    categoryId: "automate",
    description: "Visual automation platform. Build complex workflows by connecting apps with a visual drag-and-drop editor. More powerful than Zapier for complex logic.",
    bestFor: "Best for complex, multi-step automations",
    pricing: "freemium",
    priceNote: "Free tier. Core from $9/mo",
    difficulty: "intermediate",
    url: "https://make.com",
    quickStart: [
      "Sign up at make.com",
      "Create a new scenario and pick your trigger app",
      "Add action steps and connect your workflow visually",
    ],
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    categoryId: "automate",
    description: "AI built into Notion: summarize pages, generate content, fill databases, and answer questions about your workspace. Your second brain gets smarter.",
    bestFor: "Best for organizing knowledge and AI-assisted writing in one place",
    pricing: "freemium",
    priceNote: "Free Notion + AI add-on from $10/mo",
    difficulty: "beginner",
    url: "https://notion.so",
    quickStart: [
      "Open any Notion page and press Space to activate AI",
      "Try: 'Summarize this page' or 'Write a first draft about [topic]'",
      "Use AI in databases to auto-fill properties and generate insights",
    ],
  },

  // === RESEARCH AND LEARN ===
  {
    slug: "perplexity",
    name: "Perplexity",
    categoryId: "research",
    description: "AI-powered search that gives direct answers with sources. Like Google but it reads all the results for you and synthesizes a clear answer.",
    bestFor: "Best for quick research with cited sources",
    pricing: "freemium",
    priceNote: "Free tier. Pro from $20/mo",
    difficulty: "beginner",
    url: "https://perplexity.ai",
    nadiaPick: true,
    quickStart: [
      "Go to perplexity.ai",
      "Ask a question like you'd ask a smart friend: 'What's the best email marketing tool for solopreneurs under $30/mo?'",
      "Click the sources to verify and go deeper",
    ],
  },
  {
    slug: "notebooklm",
    name: "NotebookLM",
    categoryId: "research",
    description: "Google's AI notebook. Upload documents, articles, or notes and ask questions about them. It only answers from your sources, reducing hallucination.",
    bestFor: "Best for analyzing and learning from your own documents",
    pricing: "free",
    priceNote: "Completely free with Google account",
    difficulty: "beginner",
    url: "https://notebooklm.google.com",
    nadiaPick: true,
    quickStart: [
      "Go to notebooklm.google.com and sign in",
      "Create a notebook and upload PDFs, docs, or paste URLs",
      "Ask questions: 'What are the key takeaways?' or 'Summarize the main arguments'",
    ],
  },
  {
    slug: "google-ai-studio",
    name: "Google AI Studio",
    categoryId: "research",
    description: "Experiment with Google's AI models directly. Test prompts, upload files, and explore AI capabilities. Great for learning how AI works under the hood.",
    bestFor: "Best for experimenting with AI models and learning",
    pricing: "free",
    priceNote: "Free with Google account",
    difficulty: "intermediate",
    url: "https://aistudio.google.com",
    quickStart: [
      "Go to aistudio.google.com and sign in",
      "Choose a model and start a chat or structured prompt",
      "Experiment with different system instructions and parameters",
    ],
  },

  // === DESIGN YOUR BRAND ===
  {
    slug: "looka",
    name: "Looka",
    categoryId: "brand",
    description: "AI logo maker. Answer questions about your brand style and Looka generates dozens of professional logo options. Includes full brand kit.",
    bestFor: "Best for creating a professional logo in minutes",
    pricing: "freemium",
    priceNote: "Free to design. Download from $20 one-time",
    difficulty: "beginner",
    url: "https://looka.com",
    quickStart: [
      "Go to looka.com and enter your business name",
      "Choose styles, colors, and symbols you like",
      "Browse generated logos and customize your favorite",
    ],
  },

  // === MANAGE SOCIAL MEDIA ===
  {
    slug: "buffer",
    name: "Buffer",
    categoryId: "social",
    description: "Simple social media scheduling with AI caption suggestions. Plan, schedule, and analyze posts across all platforms from one dashboard.",
    bestFor: "Best for simple, no-fuss social media scheduling",
    pricing: "freemium",
    priceNote: "Free for 3 channels. Essentials from $6/mo",
    difficulty: "beginner",
    url: "https://buffer.com",
    quickStart: [
      "Sign up at buffer.com and connect your social accounts",
      "Click 'Create Post' and use AI Assistant to generate captions",
      "Schedule for optimal times and publish",
    ],
  },

  // === PRODUCTIVITY AND ORGANIZATION ===
  {
    slug: "otter",
    name: "Otter.ai",
    categoryId: "productivity",
    description: "AI meeting assistant. Records, transcribes, and summarizes meetings in real time. Generates action items and allows searching across all your meetings.",
    bestFor: "Best for meeting notes and transcription",
    pricing: "freemium",
    priceNote: "300 min free/month. Pro from $17/mo",
    difficulty: "beginner",
    url: "https://otter.ai",
    quickStart: [
      "Sign up at otter.ai and connect your calendar",
      "Otter joins your Zoom/Meet/Teams calls automatically",
      "After the meeting, review the summary and action items",
    ],
  },
  {
    slug: "granola",
    name: "Granola",
    categoryId: "productivity",
    description: "AI notepad for meetings. Take rough notes during meetings and Granola enhances them with AI: fills gaps, formats, and creates structured summaries.",
    bestFor: "Best for turning messy meeting notes into clean documents",
    pricing: "freemium",
    priceNote: "Free tier. Pro from $10/mo",
    difficulty: "beginner",
    url: "https://granola.ai",
    isNew: true,
    quickStart: [
      "Download Granola for Mac or Windows",
      "Take notes normally during your next meeting",
      "After the meeting, Granola enhances your notes with AI context",
    ],
  },
];

export const NADIAS_STACK: { slug: string; howIUseIt: string }[] = [
  { slug: "claude", howIUseIt: "Strategy, long-form writing, and building MetaHers content. My thinking partner." },
  { slug: "chatgpt", howIUseIt: "Quick tasks, brainstorming, and social media captions." },
  { slug: "midjourney", howIUseIt: "All MetaHers brand imagery and editorial visuals." },
  { slug: "canva-ai", howIUseIt: "Social media graphics, presentations, and quick design work." },
  { slug: "replit", howIUseIt: "Building the MetaHers app. From idea to deployed product." },
  { slug: "notebooklm", howIUseIt: "Research and analyzing documents for content creation." },
];
